server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_manager
    username: root
    password: monsteal48
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect